# Generated by Django 4.2.5 on 2023-09-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('descricao', models.CharField(max_length=999999999)),
                ('aplicacao', models.CharField(max_length=999999999)),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
